# Generated by Django 5.2.4 on 2025-08-03 09:18

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unikal ID')),
                ('issued_at', models.DateField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Sertifikat fayli')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs sarlavhasi')),
                ('description', models.TextField(verbose_name="Kurs haqida ma'lumot")),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Kurs rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')),
                ('progress', models.FloatField(default=0.0, verbose_name="O'zlashtirish progressi (%)")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilganmi')),
            ],
            options={
                'verbose_name': 'Kursga yozilish',
                'verbose_name_plural': 'Kursga yozilishlar',
            },
        ),
        migrations.CreateModel(
            name='FillTheBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text="Tushirib qoldirilgan so'z o'rniga {blank} yozing.", verbose_name='Savol matni')),
                ('correct_answer', models.CharField(max_length=100, verbose_name="To'g'ri javob")),
            ],
            options={
                'verbose_name': "Amaliy topshiriq (bo'shliqni to'ldirish)",
                'verbose_name_plural': "Amaliy topshiriqlar (bo'shliqni to'ldirish)",
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars sarlavhasi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Dars kontenti')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Material nomi')),
                ('file', models.FileField(upload_to='lesson_materials/', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Dars materiali',
                'verbose_name_plural': 'Dars materiallari',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Modul sarlavhasi')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Modul progressi',
                'verbose_name_plural': 'Modul progresslari',
            },
        ),
    ]
