# Generated by Django 5.2.4 on 2025-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Masalan: bxl-python, bxl-javascript', max_length=50, null=True, verbose_name='Yutuq Ikonasi Klassi (BoxIcons)'),
        ),
    ]
