"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7wqn5yuio-#6$qbzgnp7$+n45-vx+f9-3_w(*n0m2^44dl*a=^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Yaratilgan ilovalar
    'users',
    'courses',
    'main',

    # Tashqi kutubxonalar
    'ckeditor',
    'ckeditor_uploader', # Fayl yuklash uchun
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# config/settings.py faylining oxiriga qo'shing

# Statik fayllar uchun sozlamalar
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # production uchun
STATICFILES_DIRS = [
    BASE_DIR / 'static', # <-- SHU QATORNI QO'SHING
]
# Foydalanuvchi tomonidan yuklanadigan fayllar (media) uchun sozlamalar
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor fayl yuklash yo'lagi
CKEDITOR_UPLOAD_PATH = "uploads/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'


# config/settings.py faylining oxiriga qo'shing

# CKEDITOR sozlamalari
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # Yuqoridagi to'liq sozlamani ishlating
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # Rasm yuklash plagini
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}


# config/settings.py faylining oxiriga qo'shing

JAZZMIN_SETTINGS = {
    # Saytning sarlavhasi (brauzer tabida ko'rinadi)
    "site_title": "GT Admin",

    # Login ekranida va navbarning yuqorisida ko'rinadigan nom
    "site_header": "GT LMS",

    # Sayt brendi (site_header o'rniga ishlatiladi)
    "site_brand": "Tutorial Platform",

    # Admin panel uchun logo. Statik fayllar papkasida bo'lishi kerak.
    # Misol: "assets/img/logo.png"
    "site_logo": None,

    # Login ekrani uchun logo
    "login_logo": None,

    # Kirishda "Xush kelibsiz" matni
    "welcome_sign": "GT LMS'ga xush kelibsiz!",

    # Global qidiruv uchun modellar
    "search_model": ["users.User", "courses.Course"],

    # Yuqori menyudagi havolalar
    "topmenu_links": [
        # Asosiy saytga havola
        {"name": "Bosh sahifa", "url": "index", "permissions": ["auth.view_user"]},
        # Model uchun havola
        {"model": "users.User"},
    ],

    #############
    # Menyuni tartiblash
    #############
    # Ilovalarni va modellarni menyuda qanday tartibda ko'rsatish
    "order_with_respect_to": [
        # Foydalanuvchilar bloki
        "users", "users.User",

        # Kurslar bilan bog'liq asosiy modellar
        "courses", "courses.Course", "courses.Module", "courses.Lesson",

        # Darsga qo'shimcha materiallar
        "courses.LessonMaterial", "courses.FillTheBlankExercise",

        # Progress va sertifikatlar
        "courses.Enrollment", "courses.ModuleProgress", "courses.Certificate",

        # Django standart Auth (guruhlar)
        "auth",
    ],

    # Menyudagi ilovalar uchun ikonlar (Font Awesome 4.7)
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",

        "courses.Course": "fas fa-book-open",
        "courses.Module": "fas fa-puzzle-piece",
        "courses.Lesson": "fas fa-chalkboard-teacher",
        "courses.LessonMaterial": "fas fa-file-alt",
        "courses.FillTheBlankExercise": "fas fa-pen-fancy",
        "courses.Enrollment": "fas fa-user-plus",
        "courses.ModuleProgress": "fas fa-tasks",
        "courses.Certificate": "fas fa-certificate",
    },

    # Agar biror modelni admin panelda ko'rsatishni istamasangiz
    "hide_models": [],

    # Agar biror ilovani to'liq yashirmoqchi bo'lsangiz
    "hide_apps": [],

    # Model ichidagi maydonlarni tartiblash (agar kerak bo'lsa)
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}